events { }

http {
    server {
        listen 80;

        # Rediriger toutes les requêtes /api vers le Backend ASP.NET Core
        location /api/ {
            proxy_pass http://backend:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Rediriger tout le reste vers le Frontend React
        location / {
            proxy_pass http://frontend:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}